// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.12.4
// source: advert.proto

package advert_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAdvertIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerUuid     string                 `protobuf:"bytes,1,opt,name=owner_uuid,json=ownerUuid,proto3" json:"owner_uuid,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	ExpireDate    string                 `protobuf:"bytes,4,opt,name=expire_date,json=expireDate,proto3" json:"expire_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdvertIn) Reset() {
	*x = CreateAdvertIn{}
	mi := &file_advert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdvertIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdvertIn) ProtoMessage() {}

func (x *CreateAdvertIn) ProtoReflect() protoreflect.Message {
	mi := &file_advert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdvertIn.ProtoReflect.Descriptor instead.
func (*CreateAdvertIn) Descriptor() ([]byte, []int) {
	return file_advert_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAdvertIn) GetOwnerUuid() string {
	if x != nil {
		return x.OwnerUuid
	}
	return ""
}

func (x *CreateAdvertIn) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CreateAdvertIn) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *CreateAdvertIn) GetExpireDate() string {
	if x != nil {
		return x.ExpireDate
	}
	return ""
}

type CreateAdvertOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdvertOut) Reset() {
	*x = CreateAdvertOut{}
	mi := &file_advert_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdvertOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdvertOut) ProtoMessage() {}

func (x *CreateAdvertOut) ProtoReflect() protoreflect.Message {
	mi := &file_advert_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdvertOut.ProtoReflect.Descriptor instead.
func (*CreateAdvertOut) Descriptor() ([]byte, []int) {
	return file_advert_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAdvertOut) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_advert_proto protoreflect.FileDescriptor

var file_advert_proto_rawDesc = string([]byte{
	0x0a, 0x0c, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x78,
	0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x49, 0x6e,
	0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x65, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x44, 0x61, 0x74, 0x65, 0x22, 0x2b, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x4f, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0x42, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x33, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64,
	0x76, 0x65, 0x72, 0x74, 0x12, 0x0f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x76,
	0x65, 0x72, 0x74, 0x49, 0x6e, 0x1a, 0x10, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64,
	0x76, 0x65, 0x72, 0x74, 0x4f, 0x75, 0x74, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x61,
	0x64, 0x76, 0x65, 0x72, 0x74, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
})

var (
	file_advert_proto_rawDescOnce sync.Once
	file_advert_proto_rawDescData []byte
)

func file_advert_proto_rawDescGZIP() []byte {
	file_advert_proto_rawDescOnce.Do(func() {
		file_advert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_advert_proto_rawDesc), len(file_advert_proto_rawDesc)))
	})
	return file_advert_proto_rawDescData
}

var file_advert_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_advert_proto_goTypes = []any{
	(*CreateAdvertIn)(nil),  // 0: CreateAdvertIn
	(*CreateAdvertOut)(nil), // 1: CreateAdvertOut
}
var file_advert_proto_depIdxs = []int32{
	0, // 0: ChatService.CreateAdvert:input_type -> CreateAdvertIn
	1, // 1: ChatService.CreateAdvert:output_type -> CreateAdvertOut
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_advert_proto_init() }
func file_advert_proto_init() {
	if File_advert_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_advert_proto_rawDesc), len(file_advert_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_advert_proto_goTypes,
		DependencyIndexes: file_advert_proto_depIdxs,
		MessageInfos:      file_advert_proto_msgTypes,
	}.Build()
	File_advert_proto = out.File
	file_advert_proto_goTypes = nil
	file_advert_proto_depIdxs = nil
}
